name: "Build"

on:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: "write"
    strategy:
      fail-fast: false
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      -
        name: "Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      -
        name: "Setup Ghidra"
        uses: antoniovazquezblanco/setup-ghidra@v2.0.5
        with:
          version: "11.4"
      -
        name: "Build extension"
        run: cd PicoBlaze && gradle buildExtension
      -
        name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "extension"
          path: "PicoBlaze/dist/*"
          if-no-files-found: "error"
        if: ${{ !cancelled() }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - "build"
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
    steps:
      -
        name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      -
        name: "Setup JDK"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          java-package: "jre"
      -
        name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: "extension"
          path: "ext_out/"
          merge-multiple: true
      -
        name: "GitHub release"
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "ext_out/*"
          draft: true
